### ISSUE TITLE
How do I fetch the location data inside unity?

### ISSUE THREAD

**Issue by JugalRupela** [NinevaStudios/Unity-Android-Background-location-tracker#1]
Hi there, I tried to build your project I could see the notification popup. However when I try to fetch the intent data in unity, I get empty string. how can we fetch the location data inside unity?

**Comment by TarasOsiris** [comment]
@JugalRupela Hi, this project was abandoned a long time ago and also was not finished so there is a chance it's just not implemented, but I don't remember at this point :)

**Comment by JugalRupela** [comment]
Ahh I see... alright then I'll try to see if I can make it work somehow.
Thanks for making the code public though, very useful...
